<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAgente'); ?>
    <div class="ui segment vertical very padded" style="border:0">
        <div class="ui container ui segment red very padded">
            <h1 class="ui header">Carga de datos comerciales</h1>
            <div class="ui divider"></div>
            <!--<div class="ui  message">
<i class="close icon"></i>
<div class="header">
Detalles
</div>
<ul class="list">
<li>No. de archivos cargados: <strong>0</strong></li>
<li>Ultima fecha carga de archivo: <strong>11/02/2017</strong></li>
</ul>
</div>-->
            <div class="ui success message">
                <div class="header">Errores procesando archivos</div>
                <ul class="list">
                    <li>Tamaño maximo 20MB.</li>
                    <li>Extencion de archivo .txt</li>
                </ul>
            </div>
            <form action="cargar" class="ui form container text <?php echo isset($errores) ?"error" :""?> segment" enctype="multipart/form-data" method="POST">
                <div class="field">
                    <label for="adjuntar archivo">Adjuntar archivo</label>
                    <input type='file' name='informacion_comercial' id='informacion_comercial' placeholder="Selecciona el archivo" required>
                </div>
                <!--<p>Tamaño: <strong id="tam"><span id="tamano_archivo"></span></strong></p>-->
                <input type="submit" value="Finalizar" class="ui button violet" id="btn_procesar" disabled>
                <div class="ui message error">
                    <div class="header msg">Errores procesando archivos</div>
                    <ul class="list msg">
                        <?php 
                        if(isset($errores)){ 
                             foreach($errores as $error){ ?>
                        <li id="item-msg"><?php echo $error; ?></li>
                        <?php } } ?>
                    </ul>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            function verificar_archivo($campo){
                if($campo.files.length > 0){

                    $(".list.msg").empty();
                    $(".header.msg").empty();
                    $(".ui.form").removeClass("error");
                    $(".ui.form").removeClass("success");

                    var tam_kb = 1024;
                    if(($campo.files[0].size/tam_kb) > (tam_kb*20)){



                        $('.header.msg').append("Errores de archivo...");
                        $(".list.msg").append('<li id="item-msg">Archivo supera el tamaño...</li>');
                        $(".list.msg").append('<li id="item-msg">Tamaño archivo: '+(Math.round($campo.files[0].size/tam_kb))+'KB</li>');
                        $("#btn_procesar").prop("disabled", true);
                        //$(".ui.form > .ui.message").removeClass("success");
                        $(".ui.form > .ui.message").addClass("error");
                        $('.ui.form').addClass('error');
                    }else{

                        $('.header.msg').append("Mensaje informativo");
                        $(".list.msg").append('<li id="item-msg">Tamaño archivo: '+(Math.round($campo.files[0].size/tam_kb))+'KB</li>');
                        $("#btn_procesar").prop("disabled", false);
                        $(".ui.form > .ui.message").addClass("success");
                        $('.ui.form').addClass('success');
                        
                        /*$file = $campo.files[0].name.split(".");
                        $file_name = $file[0];
                        $ext = $file[1];
                        
                        console.log($file_name);
                        var id_distribuidor = $file_name.substr(0,1);
                        console.log("dist: " +id_distribuidor);
                        var cmpna = $file_name.substr(1,1);
                        console.log("campa: " +cmpna);
                        var anio = $file_name.substr(2,2);
                        console.log("anio: " +anio);
                        var mes = $file_name.substr(4,1);
                        console.log($file_name);
                        console.log("mes: " +mes);
                        var tabla = $file_name.substr(5,$file_name.length-5);
                        console.log(tabla);*/
                       // var id_distribuidor = ;
                    }
                }else{
                    var control = $("#tamano_archivo");
                    control.replaceWith(control = control.clone(true));
                    $("#btn_procesar").prop("disabled", true);
                }
            }
            $("#informacion_comercial").change(function($campo,$form){
                // console.log($campo);
                verificar_archivo($campo.target);
            });
            verificar_archivo($("#informacion_comercial")[0]);
        });
    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>