
<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAgente'); ?>
    <div class="ui segment vertical very padded">
        <div class="ui container ui segment red very padded">
            <h1 class="ui header">Archivos Recientemente Cargados</h1>
            <div class="ui divider"></div>
            <div class="ui  message">
                <!--<i class="close icon"></i>-->
                <div class="header">
                    Detalles
                </div>
                <ul class="list">
                    <li>No. de archivos cargados: <strong><?php echo count($archivos)?></strong></li>
                    <li>Ultima fecha carga de archivo: <strong><?php echo (count($archivos) > 0) ? $archivos[0]["FECHA"] : "Ninguna" ?></strong></li>
                </ul>
            </div>
           <!-- <a href="carga/" class="ui button  fluid red">Cargar Archivo</a>-->
            <table class="ui striped table black celled">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Fecha Carga</th>
                        <th>Fecha </th>
                        <th>Nombre Archivo</th>
                    </tr>
                </thead>
                <tbody style="min-height:100px !important">
                   <?php foreach($archivos as $archivo){?>
                    <tr>
                        <td><?php echo $archivo["idArchivo"] ?></td>
                        <td><?php echo $archivo["fechaCarga"] ?></td>
                        <td><?php echo $archivo["FECHA"] ?></td>
                        <td><a  class="link "><?php echo $archivo["nombreArchivo"] ?></a></td>
                    </tr>
                    <?php }?>
                </tbody>
                <tfoot>
                    <!--<tr>
                        <th colspan="4">
                            <div class="ui pagination menu">
                                <a class="item">
                                    <i class="chevron left icon"></i>
                                </a>
                                <a class="active item">
                                    1
                                </a>
                                <a class="item">
                                    2
                                </a>
                                <a class="item">
                                    3
                                </a>
                                <a class="item">
                                    ...
                                </a>
                                <a class="item">
                                    <i class="chevron right icon"></i>
                                </a>
                            </div>
                        </th>
                    </tr>-->
                </tfoot>
            </table>
        </div>
    </div>
    <script>
        $('.ui.dropdown').dropdown();
    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>