
<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAgente'); ?>
    <div class="ui segment vertical very padded">
        <div class="ui container ui segment red very padded">
            <h1 class="ui header">Archivos Recientemente Cargados</h1>
            <div class="ui divider"></div>
            <div class="ui  message">
                <!--<i class="close icon"></i>-->
                <div class="header">
                    Detalles
                </div>
                <ul class="list">
                    <li>No. de archivos cargados: <strong>0</strong></li>
                    <li>Ultima fecha carga de archivo: <strong>11/02/2017</strong></li>
                </ul>
            </div>
            <a href="carga/" class="ui button  fluid red">Cargar Archivo</a>
            <table class="ui striped table black celled">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Fecha Carga</th>
                        <th>Fecha </th>
                        <th>Nombre Archivo</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>3</td>
                        <td>05/01/2017</td>
                        <td>05/01/2017</td>
                        <td><a href="" class="link ">BC163_DATOS_COMERCIALES.txt</a></td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>05/01/2017</td>
                        <td>05/01/2017</td>
                        <td><a href="" class="link ui">BC162_DATOS_COMERCIALES.txt</a></td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>05/01/2017</td>
                        <td>05/01/2017</td>
                        <td><a class="link">BC161_DATOS_COMERCIALES.txt</a></td>
                    </tr>

                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            <div class="ui pagination menu">
                                <a class="item">
                                    <i class="chevron left icon"></i>
                                </a>
                                <a class="active item">
                                    1
                                </a>
                                <a class="item">
                                    2
                                </a>
                                <a class="item">
                                    3
                                </a>
                                <a class="item">
                                    ...
                                </a>
                                <a class="item">
                                    <i class="chevron right icon"></i>
                                </a>
                            </div>
                        </th>
                        <th>Total Registros(<strong>0</strong>)</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <script>
        $('.ui.dropdown').dropdown();
    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>