<?php \Core\Vista::parcial('header'); ?>
<body class="bg-login">
    <div class="raiz">
        <div class="form-login ui segment">
            <form class="ui large form ">

                <h2 class="ui header center aligned">
                    <i class="unlock alternate icon"></i>
                    <div class="content">
                        Iniciar Sesión
                    </div>
                </h2>
                <div class="ui divider"></div>
                <!--
<h3 class="ui center aligned icon header">
<i class="circular users icon"></i>
Iniciar Sesión
</h3>-->
                <div class="field">
                    <label>Usuario</label>
                    <div class="ui left icon input">
                        <input type="text" placeholder="Nombre de usuario" autofocus>
                        <i class="user icon"></i>
                    </div>
                </div>
                <div class="field">
                    <label>Contraseña</label>
                    <div class="ui left icon input">
                        <input type="password" placeholder="Contraseña">
                        <i class="lock icon"></i>
                    </div>
                </div>

                <div class="ui error message">
                    <div class="header">Action Forbidden</div>
                    <p>You can only sign up for an account once with a given e-mail address.</p>
                </div>
                <div class="ui submit button big fluid blue" id="btnLogin">
                    <i class="icon sign in"></i>
                    Submit</div>
            </form>

        </div>
    </div> 
    <div class="ui modal small">

        <div class="ui active dimmer">
            <div class="ui small text loader">Cargando...</div>
        </div>
    </div>
    <script src="public/assets/js/jquery-3.2.1/jquery-3.2.1.min.js"></script>
    <script src="public/assets/js/semantic-ui-2.2.10/semantic.min.js"></script>
    <script>
        $("#btnLogin").click(function(){
            $('.small.modal')
                .modal('setting', 'closable', false)
                .modal('show');
        });

    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>

