<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAdmin'); ?>
    <div class="ui segment vertical">
        <div class="ui container center aligned">
            <h1>Bienvenido</h1>
            <div class="ui divider"></div>
        </div>
    </div>
    <!--<div class="ui segment vertical red" style="margin-left:210px;">
<div class="ui container ">
<h1 class="ui header">Inicio</h1>
<div class="ui divider"></div>
<div class="ui segment">
<h2 class="ui header">Agentes</h2>
<table class="ui striped table">
<thead>
<tr>
<th>Descripcion</th>
<th>Identificación</th>
<th>Pais</th>
</tr>
</thead>
<tbody>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
</tr>
<tr>
<td>Jill Lewis</td>
<td>May 11, 2014</td>
<td>jilsewris22@yahoo.com</td>
</tr>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
</tr>
</tbody>
<tfoot class="full-width">
<tr>
<th></th>
<th colspan="3">
<div class="ui right floated small primary labeled icon button">
<i class="user icon"></i> Nuevo Agente
</div>
</th>
</tr>
</tfoot>
</table>
</div>
<div class="ui segment">
<h2 class="ui header">Cuetas de acceso</h2>
<table class="ui striped table">
<thead>
<tr>
<th>Nombres</th>
<th>Nombre Usuario</th>
<th>Tipo cuenta</th>
<th>Distribuidor</th>
</tr>
</thead>
<tbody>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
<td>No</td>
</tr>
<tr>
<td>Jamie Harington</td>
<td>January 11, 2014</td>
<td>jamieharingonton@yahoo.com</td>
<td>Yes</td>
</tr>
<tr>
<td>Jill Lewis</td>
<td>May 11, 2014</td>
<td>jilsewris22@yahoo.com</td>
<td>Yes</td>
</tr>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
<td>No</td>
</tr>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
<td>No</td>
</tr>
<tr>
<td>Jamie Harington</td>
<td>January 11, 2014</td>
<td>jamieharingonton@yahoo.com</td>
<td>Yes</td>
</tr>
<tr>
<td>Jill Lewis</td>
<td>May 11, 2014</td>
<td>jilsewris22@yahoo.com</td>
<td>Yes</td>
</tr>
<tr>
<td>John Lilki</td>
<td>September 14, 2013</td>
<td>jhlilk22@yahoo.com</td>
<td>No</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>-->
</body>
<?php \Core\Vista::parcial('footer'); ?>