<?php \Core\Vista::parcial('header'); ?>
<body>
    <div class="ui center aligned segment vertical" style="padding: 50px 0 50px 0;">
        <div class="ui container">
            <h1 class="ui header center aligned">Listado de usuarios</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus in ducimus rerum amet quod laboriosam autem architecto consectetur debitis illo fuga aspernatur, modi sed suscipit perspiciatis earum distinctio. Tempore, consequuntur?</p>
            <ui class="divider"></ui>
            <table class="ui table celled">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>nombre</th>
                        <th>telefono</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($usuarios as $usuario) { ?>
                    <tr>
                        <td><?php echo $usuario["id"] ?></td>
                        <td><?php echo $usuario["nombre"] ?></td>
                        <td><?php echo $usuario["telefono"] ?></td>

                    </tr>
                    <?php } ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            <a href="usuarios/crear" class="ui button">Agregar</a>
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</body>
<?php \Core\Vista::parcial('footer'); ?>