<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAdmin'); ?>
    <div class="ui vertical segment very padded">
        <div class="ui container">

            <div class="ui segments">
                <div class="ui segment red">
                    <h2 class="ui header">
                        <i class="ui user icon"></i>
                        <div class="content">
                            Administracion de Cuentas de usuario
                        </div>
                    </h2>
                </div>
                <div class="ui blue segment">
                    <table class="ui unstackable celled table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombres</th>
                                <th>Nombre usuario</th>
                                <th>Estado pass</th>
                                <th>Tipo Cuenta</th>
                                <th>Distribuidor</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($cuentas as $cuenta) {?>
                            <tr>
                                <td><?php echo $cuenta['idCuenta']?></td>
                                <td><?php echo $cuenta['nombres']?></td>
                                <td><?php echo $cuenta['nombreUsuario']?></td>
                                <td>
                                    <?php if($cuenta['estadoPass'] == 1){ ?>
                                    <div class="ui tiny blue horizontal label">Normal</div>
                                    <?php } else {?>
                                    <div class="ui red tiny horizontal label">Reestablecida</div></td>
                                <?php } ?>
                                <td><?php echo $cuenta['tipoCuenta']?></td>
                                <td><?php echo $cuenta['distribuidor']?></td>

                                <td class="ui center aligned">
                                    <a class="ui button teal mini " onclick='edit(<?php echo '"' . $cuenta['idCuenta'] .'","' . $cuenta['nombres'] .'","' . $cuenta['nombreUsuario'] .'","' .$cuenta['tipoCuenta'] .'","' . $cuenta['distribuidor'] .'"';?>)'>
                                        <i class="ui icon edit"></i>
                                        Editar
                                        
                                    </a>
                                    <form method="post" action="eliminarCuenta" style="display:inline" onsubmit='return confirm("Eliminar Cuenta <?php echo $cuenta["nombres"]?>?")'>
                                        <input type="text" name="idCuenta" hidden="hidden" value="<?php echo $cuenta['idCuenta'];?>">
                                        <button type="submit" class="ui button orange mini ">
                                            <i class="ui icon erase"></i>
                                            Eliminar
                                        </button>
                                    </form>
                                    <form method="post" action="reestablecerPass" style="display:inline" onsubmit='return confirm("Reestablecer contraseña de <?php echo $cuenta["nombreUsuario"]?>?")'>
                                        <input type="text" name="idCuenta" hidden="hidden" value="<?php echo $cuenta['idCuenta'];?>">
                                        <button type="submit" class="ui button mini green">
                                            <i class="icon refresh"></i>
                                            Password
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            <?php }    ?>
                        </tbody>
                        <tfoot class="full-width">
                            <tr>
                                <th colspan="7">
                                    <div class="ui black label">
                                        Registros
                                        <div class="detail">(<?php echo count($cuentas) ?>)</div>
                                    </div>
                                    <a id="btnNuevoAgente" class="ui right floated small primary labeled icon button">
                                        <i class="building icon"></i> Nueva Cuenta
                                    </a>
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form class="ui modal small frm form" method="post" action="guardarCuenta">
        <i class="close icon"></i>
        <div class="header">
            <i class="ui plus icon"></i>
            Nueva cuenta de usuario
        </div>
        <div class="content">
            <div class="ui form frm">
                <input type="text" name="idCuenta" id="idCuenta" hidden="" value="0">
                <div class="field required">
                    <label>Nombres</label>
                    <input type="text" name="nombres" id="nombres" placeholder="Nombres" autocomplete="off">
                </div>
                <div class="field required">
                    <label>Nombre de usuario</label>
                    <input type="text" name="username"  id="username" placeholder="Nombre de usuario">
                </div>

                <div class="field required">
                    <label>Tipo de cuenta</label>

                    <select name="tipoCuenta" id="tipoCuenta">
                        <option value="">Seleccionar tipo</option>
                        <?php foreach($tipoCuentas as $tipoCuenta) {?>
                        <option value="<?php echo $tipoCuenta['idTipoCuenta']; ?>"><?php echo $tipoCuenta['descripcion']?></option>
                        <?php }?>
                    </select>
                </div>
                <div class="field">
                    <label>Agente</label>

                    <select name="distribuidor" id="distribuidor">
                        <option value="">Seleccionar distribuidor</option>
                        <?php foreach($distribuidores as $distribuidor) {?>
                        <option value="<?php echo $distribuidor['idDistribuidor']; ?>"><?php echo $distribuidor['nombre']?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="ui error message"></div>
        </div>
        <div class="actions">
            <a class="ui red deny button">
                <i class="ui icon warning sign"></i>
                Cancelar</a>
            <button type="submit" class="ui blue right labeled icon button">
                <i class="ui save icon"></i>
                Guardar
            </button>

        </div>
    </form>
    <script src="/<?php echo APPNAME;?>/public/assets/js/jquery-3.2.1/jquery-3.2.1.min.js"></script>
    <script src="/<?php echo APPNAME;?>/public/assets/js/semantic-ui-2.2.10/semantic.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#btnNuevoAgente").click(function(){
                $('.small.modal')
                    .modal('setting', 'closable', false)
                    .modal('show');
                $("#idCuenta").val("0");
                $("#nombres").val("");
                $("#username").val("");
                $("#tipoCuenta").val("");
            });


            $('.ui.frm')
                .form({
                fields: {
                    nombre_agente: {
                        identifier: 'nombre_agente',
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Nombre no puede estar Vacio.'
                            }
                        ]
                    },
                    identificador: {
                        identifier: 'identificador',
                        rules: [
                            {
                                type   : 'maxLength[1]',
                                prompt : 'Identificador no puede estar vacio.'
                            },
                            {
                                type   : 'regExp[/^[A-Z-]{1,1}$/]',
                                prompt : 'Ingresar identificador valido entre A - Z'
                            }
                        ]
                    },
                    pais: {
                        identifier: 'pais',
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Pais no puede ir vacio'
                            }
                        ]
                    }
                }
            });

        });

        
        function edit($idCuenta,$nombres,$nombreUsuario,$tipoCuenta,$distribuidor){
            $('.small.modal')
                .modal('setting', 'closable', false)
                .modal('show');
            $("#idCuenta").val($idCuenta);
            $("#nombres").val($nombres);
            $("#username").val($nombreUsuario);
            $("#tipoCuenta").val($tipoCuenta);
            $('#tipoCuenta option:contains("'+ $tipoCuenta +'")').prop('selected', true);
            if($distribuidor == "")
                $distribuidor = "Seleccionar distribuidor";
            $('#distribuidor option:contains("' + $distribuidor + '")').prop('selected', true);

            //pais.val("Guatemala");
        }

        function vaciarForm(){

        }

    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>