<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAdmin'); ?>
    <div class="ui vertical segment very padded">
        <div class="ui container">

            <div class="ui segments">
                <div class="ui segment red">
                    <h2 class="ui header">
                        <i class="ui building icon"></i>
                        <div class="content">
                            Administracion de Agentes
                        </div>
                    </h2>
                </div>
                <div class="ui blue segment">
                    <table class="ui unstackable celled table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Código</th>
                                <th>Pais</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($distribuidores as $distribuidor) {?>
                            <tr>
                                <td><?php echo $distribuidor['idDistribuidor']?></td>
                                <td><?php echo $distribuidor['nombre']?></td>
                                <td><?php echo $distribuidor['codigo']?></td>
                                <td><?php echo $distribuidor['pais']?></td>
                                <td class="ui center aligned">
                                    <a class="ui button teal mini " onclick='edit(<?php echo '"' . $distribuidor['idDistribuidor'] .'","' . $distribuidor['nombre'] .'","' . $distribuidor['codigo'] .'","' .$distribuidor['pais'] .'"';?>)'>
                                        <i class="ui icon edit"></i>
                                        Editar
                                    </a>
                                    <form method="post" action="eliminarAgente" style="display:inline" onsubmit='return confirm("Eliminar <?php echo $distribuidor['nombre']?> ?")'>
                                        <input type="text" name="id" hidden="hidden" value="<?php echo $distribuidor['idDistribuidor'];?>">
                                        <button type="submit" class="ui button orange mini ">
                                            <i class="ui icon erase"></i>
                                            Eliminar
                                        </button>
                                    </form>

                                </td>
                            </tr>
                            <?php }    ?>
                        </tbody>
                        <tfoot class="full-width">
                            <tr>
                                <th colspan="5">
                                    <div class="ui black label">
                                        Registros
                                        <div class="detail">(<?php echo count($distribuidores) ?>)</div>
                                    </div>
                                    <a id="btnNuevoAgente" class="ui right floated small primary labeled icon button">
                                        <i class="building icon"></i> Nuevo Agente
                                    </a>
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form class="ui modal small frm form" method="post" action="guardarAgente" >
        <i class="close icon"></i>
        <div class="header">
            <i class="ui plus icon"></i>
            Nuevo Agente
        </div>
        <div class="content">
            <div class="ui form frm">
                <input type="text" name="id" id="idDistribuidor" hidden="" value="0">
                <div class="field required">
                    <label>Nombre</label>
                    <input type="text" name="nombre_agente" id="nombre_agente" placeholder="Nombre, Descripcion" autocomplete="off">
                </div>
                <div class="field required">
                    <label>Código Identificación (A-Z)</label>
                    <input type="text" name="identificador"  id="identificador" placeholder="Código">
                </div>
                <div class="field required">
                    <label>Pais</label>

                    <select name="pais" id="pais">
                        <option value="">Seleccionar Pais</option>
                        <?php foreach($paises as $pais) {?>
                        <option value="<?php echo $pais['idPais']; ?>"><?php echo $pais['nombre']?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="ui error message"></div>
        </div>
        <div class="actions">
            <a class="ui red deny button">
                <i class="ui icon warning sign"></i>
                Cancelar</a>
            <button type="submit" class="ui blue right labeled icon button">
                <i class="ui save icon"></i>
                Guardar
            </button>

        </div>
    </form>
    <script src="/<?php echo APPNAME;?>/public/assets/js/jquery-3.2.1/jquery-3.2.1.min.js"></script>
    <script src="/<?php echo APPNAME;?>/public/assets/js/semantic-ui-2.2.10/semantic.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#btnNuevoAgente").click(function(){
                $('.small.modal')
                    .modal('setting', 'closable', false)
                    .modal('show');
                $("#idDistribuidor").val("0");
                $("#nombre_agente").val("");
                $("#identificador").val("");
                $("#pais").val("");
            });


            $('.ui.frm')
                .form({
                fields: {
                    nombre_agente: {
                        identifier: 'nombre_agente',
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Nombre no puede estar Vacio.'
                            }
                        ]
                    },
                    identificador: {
                        identifier: 'identificador',
                        rules: [
                            {
                                type   : 'maxLength[1]',
                                prompt : 'Identificador no puede estar vacio.'
                            },
                            {
                                type   : 'regExp[/^[A-Z-]{1,1}$/]',
                                prompt : 'Ingresar identificador valido entre A - Z'
                            }
                        ]
                    },
                    pais: {
                        identifier: 'pais',
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Pais no puede ir vacio'
                            }
                        ]
                    }
                }
            });

        });

        function edit($id,$nombre,$codigo,$pais){
            $('.small.modal')
                .modal('setting', 'closable', false)
                .modal('show');
            $("#idDistribuidor").val($id);
            $("#nombre_agente").val($nombre);
            $("#identificador").val($codigo);
            pais = $('#pais option:contains("' + $pais + '")').prop('selected', true);;

            //pais.val("Guatemala");
        }

        function vaciarForm(){

        }

    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>