<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title><?php echo $titulo; ?></title>
        <link rel="stylesheet" href="/<?php echo APPNAME; ?>/public/assets/css/semantic-ui-2.2.10/semantic.min.css">
        <link rel="stylesheet" href="/<?php echo APPNAME; ?>/public/assets/css/estilos.css">
        <script src="/<?php echo APPNAME; ?>/public/assets/js/jquery-3.2.1/jquery-3.2.1.min.js"></script>
        <script src="/<?php echo APPNAME; ?>/public/assets/js/semantic-ui-2.2.10/semantic.min.js"></script>
        <script>
            $(document).ready(function(){
                $('.ui.dropdown').dropdown(); 
            });
        </script>
    </head>
    <body>