<div class="ui left fixed vertical menu">
    <div class="item">
        <img class="ui mini image" src="/<?php echo APPNAME; ?>/public/assets/img/Circled User Male_48px.png">
    </div>
    <a class="item" href="/<?php echo APPNAME;?>/public/admin">
        <i class="ui icon home"></i>
        Inicio</a>
    <a class="item" href="/<?php echo APPNAME;?>/public/admin/agentes">
        <i class="ui icon building"></i>
        Agentes</a>
    <a class="item" href="/<?php echo APPNAME;?>/public/admin/cuentas">
        <i class="icon user"></i>
        Cuentas</a>
    <a class="item" href="/<?php echo APPNAME;?>/public/admin/salir">
        <i class="icon sign out"></i>
        Salir</a>
</div>