
<?php \Core\Vista::parcial('header'); ?>
<body>
    <?php \Core\Vista::parcial('navAnalista'); ?>
    <div class="ui segment vertical " style="border:none;">

        <div class="ui container ui segment red very padded">
            <h1 class="ui header">Distribuidores</h1>
            <div class="ui divider"></div>
            <!--<div class="ui fluid action input">
<input type="text" placeholder="buscar...">
<div class="ui button blue">Buscar</div>
</div>-->
            <div class="ui divider hidden"></div>

            <div class="ui divided list">
                <?php foreach($distribuidores as $distribuidor){ ?>
                <div class="item">
                    <a class="header" href="/<?php echo APPNAME; ?>/analista/informaciondistribuidor/<?php echo $distribuidor["codigo"]; ?>">
                    <?php echo $distribuidor["nombre"]; ?>
                    </a>
                    <?php echo $distribuidor["pais"]; ?>
                </div>
                <?php }?>
            </div>


        </div>
    </div>
    <script>
        $('.ui.dropdown').dropdown();
    </script>
</body>
<?php \Core\Vista::parcial('footer'); ?>